name: XML Validation

on:
  push:
    branches:
      - main  # Adjust to your repository's main branch

jobs:
  xml-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate XML
        run: xmllint --noout xmlvalidation/sqlmapper/**/*.xml

      - name: Check Validation Result
        run: |
          if [ $? -ne 0 ]; then
            echo "XML validation failed. Aborting commit."
            exit 1
          fi


