name: XML Validation

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  xml-validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate XML
      run: |
        # Install xmllint
        sudo apt-get update
        sudo apt-get install -y libxml2-utils

        # Validate XML files using xmllint
        xmllint --noout path/to/your/xml/files/**/*.xml

